title: Le github page of goodie
author: Godie
theme: minima
email: godie@notitec.info
description: > # this means to ignore newlines until "baseurl:"
  Esta es una descripcion para la pagina de github para que salga en los buscadores vamo a ver que tal.

# social links
twitter_username: godi # DO NOT include the @ character, or else the build will fail!
github_username:  goodie # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
